### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by quyenxhuynh** [quyenxhuynh/invit.io#16]
- [x] Username case insensitivity? 
- [x] User profiles on registration
- [x] Update user settings (+profile picture)
- [x] Create individual profiles for each user w/ public urls
- [x] Fix profiles UI
- [x] Fix messages UI - quyen
- [x] URL rewriting - quyen 
- [x] messages - quyen
- [x] New events - alex
- [ ] Event sorting - alex (moving to next assignment)
- [ ] Index 
- [ ] Username validation - no symbols? If so, then maybe need to use htmlspecialchars()
- [x] no duplicate emails (similar to sign-up.php //  line 10-20) - alex
- [ ] Event symbols -> htmlspecialchars?
- [ ] Notifications? 
- [x] make sure it works in gcp - alex
- [ ] edit loc field and add autocomplete - alex (moving to next assignment)
- [x] delete an account and event - alex (can delete events, didn't add deleting accounts yet)
- [x] Update fields
- [ ] add better events for the demo - alex

**Comment by quyenxhuynh** [comment]
- [x] (9 points) — Correctly and properly implement **at least three** of the following requirements (3 points each):

> - [x] Use array(s), may be one-dimensional arrays or multi-dimensional arrays
> - [x] Use expressions
> - [x] Use control structures (selection and loop)
> - [x] Use predefined / standard function(s)
- [x] (5 points) — Correctly and properly implement and use at least one user-defined function
- [x] (10 points) — Correctly and properly use the following implicit objects:
>  - [x] (5 points) $_GET
>  - [x] (5 points) $_POST
- [x] (16 points) — Appropriate server-side input validation
>  - [x] (12 points) Properly validate form data
>  > - [x] (4 points) Provide user-appropriate error messages
>  > - If no error message is provided, other reasonable and appropriate handling (such as auto-complete or auto-correction with defaults) and / or some forms of user-appropriate feedback are acceptable.
- [x] (25 points) — Proper implementation of form submission and handling
- [x] (25 points) — Correctly implement and properly support multiple users, using the server-side $_SESSION object
- [x] (15 points) — Correctly implement and properly maintain state of the application using at least one of the following mechanisms
> - [x] $_COOKIE
> - [x] URL rewriting
> - [x] Hidden form field(s)
- [x] (30 points) — Correctly implement and properly support multiple sessions, using a relational database
> - [x] (10 points) Users must be able to retrieve and view data previously stored in a database and use them in some ways to serve some purposes
> -  This must be done through the interface of your system, not direct access to the database.
> - [x] (10 points) Users must be able to add data to the database; i.e., data being stored must reflect the user inputs and / or the application states.
>  - This must be done through the interface of your system, not direct access to the database.
> - [x] (10 points) Users must be able to update and / or delete data stored in the database; i.e., data being stored must reflect the user inputs and / or the application states.
> - This must be done through the interface of your system, not direct access to the database.
- [ ] (5 points) — Adherence to all usability concepts as discussed in class
- [ ] (5 points) — Use good coding style: readability, style, and maintainability
> - [ ] Make identifier names understandable
> - [ ] Use proper and consistent indentation
> - [ ] Use comments
> - [ ] Use carriage return
- [ ] (15 points) — User demonstration
> - [ ] (10 points) Program is demonstrated clearly
> - [ ] (5 points) Code segments clearly explained
- [ ] [10 extra credits] — GCP
> - [ ] (8 points) — Host your app on GCP
> - [ ] (2 points) — Submit a URL to your app hosted on GCP and use it to demo your app
